name: Code Coverage

on: [push, pull_request]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pytest-cov
        pip install .[extra] --use-feature=in-tree-build
    - name: Test with pytest with coverage
      run: |
        pytest --cov=./
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    
