name: Mac

on: [push, pull_request]

jobs:
  build:
  
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew install cmake libomp
        python -m pip install --upgrade pip
        pip install pytest
        pip install .[extra]
        brew install lightgbm
    - name: Test with pytest with coverage
      run: |
        pytest
